QueryDefinitions:

TIProviders:
  OTX:
    Args:
      AuthKey: "***REMOVED***"
    Primary: True
    Provider: "OTX" # Explicitly name provider to override
  VirusTotal:
    Args:
      AuthKey: "***REMOVED***"
    Primary: True
    Provider: "VirusTotal"
  XForce:
    Args:
      ApiID: "d99c9637-3049-4c1e-b608-18c3bad769f9"
      AuthKey: "f3531662-7849-4080-9e79-b728daadc2e8"
    Primary: True
    Provider: "XForce"
  AzureSentinel:
    Args:
      WorkspaceID: "a927809c-8142-43e1-96b3-4ad87cfe95a3"
      TenantID: "35a9e601-82db-42da-b521-efc4a2f6783c"
    Primary: False
    Provider: "AzSTI"